import{a as x,S as $,i as c}from"./assets/vendor-DnCMJMY2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const A="55663277-19ff75ff764545e0f4b912e24";async function u(o,t){const{data:r}=await x.get("https://pixabay.com/api/",{params:{key:A,q:`${o}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:`${t}`,per_page:15}});return r}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),B=new $(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:r,largeImageURL:a,tags:e,likes:s,views:i,comments:b,downloads:w})=>`
            <li class="gallery-item">
                <a href="${a}">
                    <img src="${r}" alt="${e}" />
                </a>
                <p>Likes: ${s}</p>
                <p>Views: ${i}</p>
                <p>Comments: ${b}</p>
                <p>Downloads: ${w}</p>
            </li>
        `).join("");m.insertAdjacentHTML("beforeend",t),B.refresh()}function S(){m.innerHTML=""}function g(){f.classList.remove("hidden")}function p(){f.classList.add("hidden")}function E(){h.classList.remove("hidden")}function l(){h.classList.add("hidden")}const q=document.querySelector(".form"),d=document.querySelector(".load-more-btn");q.addEventListener("submit",v);d.addEventListener("click",M);let n=1,L="";async function v(o){o.preventDefault();const t=o.currentTarget.elements["search-text"].value.trim();if(t){n=1,L=t,S(),l(),g();try{const{hits:r,totalHits:a}=await u(t,n);r.length>0?(y(r),F(n,a)):(l(),c.show({color:"#EF4040",messageColor:"#FAFAFB",message:"Sorry, there are no images matching your search query. Please try again!",maxWidth:"322px"}))}catch(r){c.show({color:"#EF4040",messageColor:"#FAFAFB",message:`${r.message}`,maxWidth:"322px"})}finally{o.target.reset(),p()}}}async function M(){n++,d.disabled=!0,l(),g();try{const{hits:o,totalHits:t}=await u(L,n);console.log({hits:o,totalHits:t}),y(o);const r=document.querySelector(".gallery-item");if(r){const a=r.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}F(n,t)}catch(o){c.show({color:"#EF4040",messageColor:"#FAFAFB",message:`${o.message}`,maxWidth:"322px"})}finally{p(),d.disabled=!1}}function F(o,t){o*15>=t?(l(),c.show({color:"#EF4040",messageColor:"#FAFAFB",message:"We're sorry, but you've reached the end of search results.",maxWidth:"322px"})):E()}
//# sourceMappingURL=index.js.map
