import{a as w,S as b,i as c}from"./assets/vendor-DnCMJMY2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const x="55663277-19ff75ff764545e0f4b912e24";async function d(o,t){const{data:r}=await w.get("https://pixabay.com/api/",{params:{key:x,q:`${o}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:`${t}`,per_page:15}});return r}const u=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more-btn"),$=new b(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(({webformatURL:r,largeImageURL:a,tags:e,likes:s,views:i,comments:L,downloads:F})=>`
            <li class="gallery-item">
                <a href="${a}">
                    <img src="${r}" alt="${e}" />
                </a>
                <p>Likes: ${s}</p>
                <p>Views: ${i}</p>
                <p>Comments: ${L}</p>
                <p>Downloads: ${F}</p>
            </li>
        `).join("");u.insertAdjacentHTML("beforeend",t),$.refresh()}function A(){u.innerHTML=""}function y(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}function B(){f.classList.remove("hidden")}function S(){f.classList.add("hidden")}const E=document.querySelector(".form"),q=document.querySelector(".load-more-btn");E.addEventListener("submit",v);q.addEventListener("click",M);let n=1,l="";async function v(o){o.preventDefault();const t=o.currentTarget.elements["search-text"].value.trim();if(t){l!==t&&(n=1,l=t,A()),y();try{const{hits:r,totalHits:a}=await d(t,n);r.length>0?(h(r),g(n,a)):c.show({color:"#EF4040",messageColor:"#FAFAFB",message:"Sorry, there are no images matching your search query. Please try again!",maxWidth:"322px"})}catch(r){c.show({color:"#EF4040",messageColor:"#FAFAFB",message:`${r.message}`,maxWidth:"322px"})}finally{o.target.reset(),p()}}}async function M(){n+=1,y();try{const{hits:o,totalHits:t}=await d(l,n);h(o);const r=document.querySelector(".gallery-item");if(r){const a=r.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}g(n,t)}catch(o){c.show({color:"#EF4040",messageColor:"#FAFAFB",message:`${o.message}`,maxWidth:"322px"})}finally{p()}}function g(o,t){o*15>=t?(S(),c.show({color:"#EF4040",messageColor:"#FAFAFB",message:"We're sorry, but you've reached the end of search results.",maxWidth:"322px"})):B()}
//# sourceMappingURL=index.js.map
